src/Drifty_CLI.java
This is the implementation of feature #28 
Looking forward to your feedback. :)
=> Added an option to preserve original filename

index.html
hey created the footers
Fixes #9
=> footers added

README.md
Updated README to provide steps to deal with the MS Defender Unsafe Warning While downloading. Which previously not letting one download the .exe file. 
Let me know if i should make any changes there. TY😄
=> Updated readme to deal with download warning

Website/index.html
This is my solution to the bug posted [here](https://github.com/SaptarshiSarkar12/Drifty/issues/44)
* I have changed the transition to make it less abrupt and to make the size transformation prettier to look at.
* I have changed the cursor of the navbar elements to a pointer cursor.
=> navbar animations fixed

Website/index.html, Website/script.js, Website/style.css
* I have organized the css
* I have added semantic html to the footer
* I fixed the dark mode toggle ( Currently if you activate the bright mode and reload the page the darkmode toggle is inverted and causes you to have errors when changing themes. )
* I have deleted unused css
These changes make it easier to locate the css when another contributor wants to support the project.
=> Multiple changes

README.md
Move the `contributing` section after `demo`, as it is more likely for the users to go through it before potential contributors. 
Now the `Contributing` and `Thanks to all contributors` sections are side by side (up-down), making it looks cooler and better.
=> update: move "contributing" after "demo" in Readme

README.md
Some much needed grammatical and other improvements to the README.md file
=> Improved the README file

Website/README.md
**In simple words, we can describe a README file as a guide that gives users a detailed description of a project you have worked on.**
**It can also be described as documentation with guidelines on how to use a project. Usually it will have instructions on how to install and run the project but we're already worked on it which is the main README file our project.**
- This  section contain information of website like how's your website look like, you can see instructions videos, layers section and lots of images that are used to make website and lot more options
- and this website section also contain files like html, css, and js by which you can make necessary changes in this project
=> README.md file of Website update

README.md
Moved and organized the badges in README.md.
=> update(readme.md): organized badges

.github/workflows/pages.yml, Website/style.css
#58 As the nav scroll was fixed I have been checking what could be improved and I have fixed the transition of the footer links.
=> footer links transition fixed

Website/index.html
Everything is fine manually tested on localhost.
=> Updated footer copyright year -> manual to dynamic

Website/index.html
made download button on par with the page design
=> Fixed download button 

Website/style.css
Added code in the style.css file for solving issue #107 which was assigned to me. Also there was another bug that, the info section was overlapping with the download section so fixed that also. Please merge it under hacktoberfest. THANKS!!
=> bug fixing (issue #107)

Website/index.html, Website/script.js, Website/style.css
This completes the dynamic loading for alternative downloads in download section of the website
=> Added dynamic release loading feature #113

Website/index.html, Website/style.css
Hello @SaptarshiSarkar12 . I have added a decent styling to the footer icons by adding a fill-in effect on hover with accurate color codes. Kindly review my PR.
=> Added accurate color coding fill-in effect to social media icons in the footer.

src/FileDownloader.java
=> Fix youtube download progress bar

Website/index.html, Website/style.css
Please merge this request. I have added the animation.
=> Added animation to heading Drifty

Website/about.css, Website/about.html, Website/index.html
i have created about page as a new `about.html` file. you can check here and share your reviews. if you found it good then please merge this PR. later i will improve it using another issue. @SaptarshiSarkar12
=> About page created using Readme.md file

Website/index.html
=> Fix Menu Bar Items

src/Drifty_CLI.java, src/FileDownloader.java
Feature added to name the YouTube video to be downloaded
=> #190 Renaming downloaded YouTube videos

Website/responsive-nav.css, Website/style.css
Fixed typing mistake in CSS property : background-position-x
Changed min-device-width to min-width and vice versa as device-width is deprecated.
=> [Website] Fixed CSS Validation Errors

Website/style.css, src/utility/DriftyUtility.java
Drifty website in IPad Air or IPad Mini, the design collapses or website is non-responsive for that width and height. fixed
=> Responsive issue  img-layer class overflow solve

Website/style.css
Initially no hover effect for mode selector icon
https://user-images.githubusercontent.com/92843270/232401171-c093d486-4eed-4be6-a3b6-5e3bba8e82af.mp4
Updated the effect to cursor pointer also works in responsive design
https://user-images.githubusercontent.com/92843270/232402638-1fe4bd02-85e6-4b0d-aab6-655360e4c1f9.mp4
=> Added hover effect to light/dark mode icon

Website/app/Releases.js
=> Fix: Alignment of "Download Now" buttons in the Website

Website/app/Header.js, Website/app/layout.js
Fixes #334 
I tested the responsiveness after the change and found no other visual bugs caused by this change.
=> Removing the navigation bar overflow

Website/app/MainSection.js, Website/app/Releases.js
Fixes #734 
In this second image the first button is on hover, this is to see the new colors.
In the last screenshot the last two buttons are in hover to see the new hover colors.
@SaptarshiSarkar12 please check it.
The changes in MainSection.js are minimal and not visually noticeable. 
They are improvements for better readability of the TailwindCSS code
=> feat: Update download page for consistency across the website
